apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- monitoring.yaml
- webapp.yaml
- logging.yaml
- pod-security.yaml
- cluster-network-policies