apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: webapp-dev
resources:
  - ../../base 
  - hpa-webapp.yaml        # ← changed from bases to resources
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: webapp
  - path: patch-security-webapp.yaml
    target:
      kind: Deployment
      name: webapp
  - path: patch-webapp-resources.yaml
    target:
      kind: Deployment
      name: webapp
  - path: patch-namespace-psa.yaml
    target:
      kind: Deployment
      name: webapp