apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: event-exporter
  namespace: monitoring
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: event-exporter
    namespace: monitoring
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        labels:
          release: prometheus-stack
