apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: online-boutique-dev
namespace: online-boutique
# Point to the base directory
resources:
  - ../../base/   # ← relative path to base kustomization.yaml

# Apply the patch on top of base
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: online-boutique